-- Align already-deployed #13 state with the complete frozen-runtime contract.
alter table public.tasks drop constraint tasks_task_type_check;
alter table public.tasks add constraint tasks_task_type_check check (task_type in ('draft_brief','draft_script','prepare_visual_brief','draft_storyboard','generate_a_roll','generate_b_roll','generate_narration','extract_embedded_audio','generate_soundtrack','generate_review_render','generate_final_render','prepare_publish_package','verify_publish_package'));

create or replace function public.orchestrate_review_render_tasks(p_episode_id uuid default null)
returns setof public.tasks language plpgsql security definer set search_path = '' as $$
declare candidate record; created_task public.tasks; members jsonb; inputs jsonb; composition public.review_render_composition_revisions; project_path text; render_path text; default_revision integer;
begin
  for candidate in select episode.id as episode_id, package.id as pre_render_review_package_id, package.context_snapshot from public.episodes episode join lateral (select package.* from public.review_packages package join public.approvals approval on approval.review_package_id=package.id and approval.stage='render_ready' and approval.decision='approved' where package.episode_id=episode.id and package.stage='production_ready' and package.invalidated_at is null order by package.revision_number desc limit 1) package on true where episode.stage='render_ready' and (p_episode_id is null or episode.id=p_episode_id) order by episode.updated_at,episode.id for update of episode skip locked loop
    select coalesce(max((task.input_snapshot #>> '{review_render,project_revision}')::integer),0)+1 into default_revision from public.tasks task where task.episode_id=candidate.episode_id and task.task_type='generate_review_render' and task.input_snapshot #>> '{review_render,pre_render_review_package_id}'=candidate.pre_render_review_package_id::text;
    insert into public.review_render_composition_revisions (episode_id,pre_render_review_package_id,revision_number,caption_style,pacing,crop,transition,layout,reason) values (candidate.episode_id,candidate.pre_render_review_package_id,default_revision,'cinematic','standard','cover','fade','lower_third','默认合成配置。') on conflict (pre_render_review_package_id,revision_number) do nothing;
    select * into composition from public.review_render_composition_revisions where pre_render_review_package_id=candidate.pre_render_review_package_id order by revision_number desc limit 1;
    if exists (select 1 from public.tasks task where task.episode_id=candidate.episode_id and task.task_type='generate_review_render' and task.input_snapshot #>> '{review_render,composition_revision_id}'=composition.id::text) then continue; end if;
    select coalesce(jsonb_agg(jsonb_build_object('member_key',member.member_key,'member_kind',member.member_kind,'relative_path',coalesce(member.evidence_snapshot #>> '{artifact,relative_path}',member.evidence_snapshot #>> '{audio_track,relative_path}'),'sha256',coalesce(member.evidence_snapshot #>> '{artifact,sha256}',member.evidence_snapshot #>> '{audio_track,sha256}'),'start_seconds',coalesce((member.evidence_snapshot #>> '{audio_track,start_seconds}')::numeric,0),'duration_seconds',coalesce((member.evidence_snapshot #>> '{audio_track,duration_seconds}')::numeric,(member.evidence_snapshot #>> '{shot,durationSeconds}')::numeric)) order by member.member_key),'[]'::jsonb),coalesce(jsonb_agg(jsonb_build_object('artifactType',case when member.artifact_id is null then 'audio_track' else member.evidence_snapshot #>> '{artifact,artifact_type}' end,'relativePath',coalesce(member.evidence_snapshot #>> '{artifact,relative_path}',member.evidence_snapshot #>> '{audio_track,relative_path}'),'sha256',coalesce(member.evidence_snapshot #>> '{artifact,sha256}',member.evidence_snapshot #>> '{audio_track,sha256}'),'fileSize',coalesce((member.evidence_snapshot #>> '{artifact,file_size}')::bigint,(member.evidence_snapshot #>> '{audio_track,file_size}')::bigint)) order by member.member_key),'[]'::jsonb) into members,inputs from public.pre_render_review_members member join public.pre_render_review_member_decisions decision on decision.review_package_id=member.review_package_id and decision.member_key=member.member_key and decision.decision='approved' where member.review_package_id=candidate.pre_render_review_package_id;
    if jsonb_array_length(members)=0 or jsonb_array_length(inputs)<>jsonb_array_length(members) then continue; end if;
    project_path:=format('episodes/%s/review-render/v%s/index.html',candidate.episode_id,composition.revision_number); render_path:=format('episodes/%s/review-render/v%s/review-render.mp4',candidate.episode_id,composition.revision_number);
    insert into public.tasks (episode_id,task_type,status,input_snapshot,budget_limit_cents,max_attempts,provider,model,prompt_version) values (candidate.episode_id,'generate_review_render','ready',jsonb_build_object('capability','review_rendering','allowed_tools',jsonb_build_array('read','write'),'review_render',jsonb_build_object('pre_render_review_package_id',candidate.pre_render_review_package_id,'composition_revision_id',composition.id,'project_revision',composition.revision_number,'project_relative_path',project_path,'storyboard',candidate.context_snapshot->'storyboard','members',members,'adjustments',jsonb_build_object('caption_style',composition.caption_style,'pacing',composition.pacing,'crop',composition.crop,'transition',composition.transition,'layout',composition.layout,'reason',composition.reason)),'input_artifacts',inputs,'output',jsonb_build_object('required_artifact_types',jsonb_build_array('render','review_render_project','review_render_runtime','review_qc_report'),'content_type','video/mp4','relative_path',render_path,'review_stage','qc_review')),0,1,'hyperframes','hyperframes@0.7.109','review-render-v2') returning * into created_task; return next created_task;
  end loop;
end; $$;

create or replace function public.orchestrate_final_render_tasks(p_episode_id uuid default null)
returns setof public.tasks language plpgsql security definer set search_path = '' as $$
declare candidate record; created_task public.tasks; output_path text; project_path text;
begin
  for candidate in select episode.id as episode_id,package.id as package_id,source.input_snapshot as source_snapshot,project_artifact.*,runtime_artifact.relative_path as runtime_relative_path,runtime_artifact.sha256 as runtime_sha256,runtime_artifact.file_size as runtime_file_size,qc_artifact.relative_path as qc_relative_path,qc_artifact.sha256 as qc_sha256,qc_artifact.file_size as qc_file_size from public.episodes episode join lateral (select package.* from public.review_packages package join public.approvals approval on approval.review_package_id=package.id and approval.stage='qc_passed' and approval.decision='approved' where package.episode_id=episode.id and package.stage='qc_review' and package.invalidated_at is null order by package.revision_number desc limit 1) package on true join public.tasks source on source.id=package.task_id and source.status='completed' join public.artifacts project_artifact on project_artifact.producer_task_id=source.id and project_artifact.artifact_type='review_render_project' join public.artifacts runtime_artifact on runtime_artifact.producer_task_id=source.id and runtime_artifact.artifact_type='review_render_runtime' join public.artifacts qc_artifact on qc_artifact.producer_task_id=source.id and qc_artifact.artifact_type='review_qc_report' where episode.stage='qc_passed' and (p_episode_id is null or episode.id=p_episode_id) order by episode.updated_at,episode.id for update of episode skip locked loop
    if exists (select 1 from public.tasks task where task.episode_id=candidate.episode_id and task.task_type='generate_final_render' and task.input_snapshot #>> '{final_render,source_review_package_id}'=candidate.package_id::text) then continue; end if;
    project_path:=format('episodes/%s/final-render/v%s/index.html',candidate.episode_id,candidate.source_snapshot #>> '{review_render,project_revision}'); output_path:=format('episodes/%s/final-render/v%s/final-render.mp4',candidate.episode_id,candidate.source_snapshot #>> '{review_render,project_revision}');
    insert into public.tasks (episode_id,task_type,status,input_snapshot,budget_limit_cents,max_attempts,provider,model,prompt_version) values (candidate.episode_id,'generate_final_render','ready',jsonb_build_object('capability','final_rendering','allowed_tools',jsonb_build_array('read','write'),'final_render',jsonb_build_object('source_review_package_id',candidate.package_id,'source_project',jsonb_build_object('artifact_type',candidate.artifact_type,'relative_path',candidate.relative_path,'sha256',candidate.sha256,'file_size',candidate.file_size),'source_runtime',jsonb_build_object('artifact_type','review_render_runtime','relative_path',candidate.runtime_relative_path,'sha256',candidate.runtime_sha256,'file_size',candidate.runtime_file_size),'source_qc_report',jsonb_build_object('artifact_type','review_qc_report','relative_path',candidate.qc_relative_path,'sha256',candidate.qc_sha256,'file_size',candidate.qc_file_size),'project_relative_path',project_path,'project_revision',(candidate.source_snapshot #>> '{review_render,project_revision}')::integer,'review_render',candidate.source_snapshot->'review_render'),'input_artifacts',(candidate.source_snapshot->'input_artifacts')||jsonb_build_array(jsonb_build_object('artifactType',candidate.artifact_type,'relativePath',candidate.relative_path,'sha256',candidate.sha256,'fileSize',candidate.file_size),jsonb_build_object('artifactType','review_render_runtime','relativePath',candidate.runtime_relative_path,'sha256',candidate.runtime_sha256,'fileSize',candidate.runtime_file_size),jsonb_build_object('artifactType','review_qc_report','relativePath',candidate.qc_relative_path,'sha256',candidate.qc_sha256,'fileSize',candidate.qc_file_size)),'output',jsonb_build_object('required_artifact_types',jsonb_build_array('final_render','final_render_project','final_qc_report'),'content_type','video/mp4','relative_path',output_path,'review_stage','qc_passed')),0,1,'hyperframes','hyperframes@0.7.109','final-render-v1') returning * into created_task; return next created_task;
  end loop;
end; $$;

revoke all on function public.orchestrate_review_render_tasks(uuid), public.orchestrate_final_render_tasks(uuid) from public, anon, authenticated;
grant execute on function public.orchestrate_review_render_tasks(uuid), public.orchestrate_final_render_tasks(uuid) to service_role;
