alter table public.tasks drop constraint tasks_task_type_check;
alter table public.tasks add constraint tasks_task_type_check check (task_type in ('draft_brief', 'draft_script', 'prepare_visual_brief', 'draft_storyboard', 'generate_a_roll', 'generate_b_roll', 'generate_narration', 'extract_embedded_audio', 'generate_soundtrack', 'generate_review_render', 'generate_final_render', 'prepare_publish_package', 'verify_publish_package'));

create or replace function public.orchestrate_review_render_tasks(p_episode_id uuid default null)
returns setof public.tasks language plpgsql security definer set search_path = '' as $$
declare candidate record; created_task public.tasks; members jsonb; inputs jsonb; composition public.review_render_composition_revisions; project_path text; render_path text; default_revision integer;
begin
  for candidate in select episode.id as episode_id, package.id as pre_render_review_package_id, package.context_snapshot from public.episodes episode join lateral (select package.* from public.review_packages package join public.approvals approval on approval.review_package_id = package.id and approval.stage = 'render_ready' and approval.decision = 'approved' where package.episode_id = episode.id and package.stage = 'production_ready' and package.invalidated_at is null order by package.revision_number desc limit 1) package on true where episode.stage = 'render_ready' and (p_episode_id is null or episode.id = p_episode_id) order by episode.updated_at, episode.id for update of episode skip locked loop
    select coalesce(max((task.input_snapshot #>> '{review_render,project_revision}')::integer), 0) + 1 into default_revision from public.tasks task where task.episode_id = candidate.episode_id and task.task_type = 'generate_review_render' and task.input_snapshot #>> '{review_render,pre_render_review_package_id}' = candidate.pre_render_review_package_id::text;
    insert into public.review_render_composition_revisions (episode_id, pre_render_review_package_id, revision_number, caption_style, pacing, crop, transition, layout, reason) values (candidate.episode_id, candidate.pre_render_review_package_id, default_revision, 'cinematic', 'standard', 'cover', 'fade', 'lower_third', '默认合成配置。') on conflict (pre_render_review_package_id, revision_number) do nothing;
    select * into composition from public.review_render_composition_revisions where pre_render_review_package_id = candidate.pre_render_review_package_id order by revision_number desc limit 1;
    if exists (select 1 from public.tasks task where task.episode_id = candidate.episode_id and task.task_type = 'generate_review_render' and task.input_snapshot #>> '{review_render,composition_revision_id}' = composition.id::text) then continue; end if;
    select coalesce(jsonb_agg(jsonb_build_object('member_key', member.member_key, 'member_kind', member.member_kind, 'relative_path', coalesce(member.evidence_snapshot #>> '{artifact,relative_path}', member.evidence_snapshot #>> '{audio_track,relative_path}'), 'sha256', coalesce(member.evidence_snapshot #>> '{artifact,sha256}', member.evidence_snapshot #>> '{audio_track,sha256}'), 'start_seconds', coalesce((member.evidence_snapshot #>> '{audio_track,start_seconds}')::numeric, 0), 'duration_seconds', coalesce((member.evidence_snapshot #>> '{audio_track,duration_seconds}')::numeric, (member.evidence_snapshot #>> '{shot,durationSeconds}')::numeric)) order by member.member_key), '[]'::jsonb), coalesce(jsonb_agg(jsonb_build_object('artifactType', case when member.artifact_id is null then 'audio_track' else member.evidence_snapshot #>> '{artifact,artifact_type}' end, 'relativePath', coalesce(member.evidence_snapshot #>> '{artifact,relative_path}', member.evidence_snapshot #>> '{audio_track,relative_path}'), 'sha256', coalesce(member.evidence_snapshot #>> '{artifact,sha256}', member.evidence_snapshot #>> '{audio_track,sha256}'), 'fileSize', coalesce((member.evidence_snapshot #>> '{artifact,file_size}')::bigint, (member.evidence_snapshot #>> '{audio_track,file_size}')::bigint)) order by member.member_key), '[]'::jsonb) into members, inputs from public.pre_render_review_members member join public.pre_render_review_member_decisions decision on decision.review_package_id = member.review_package_id and decision.member_key = member.member_key and decision.decision = 'approved' where member.review_package_id = candidate.pre_render_review_package_id;
    if jsonb_array_length(members) = 0 or jsonb_array_length(inputs) <> jsonb_array_length(members) then continue; end if;
    project_path := format('episodes/%s/review-render/v%s/index.html', candidate.episode_id, composition.revision_number); render_path := format('episodes/%s/review-render/v%s/review-render.mp4', candidate.episode_id, composition.revision_number);
    insert into public.tasks (episode_id, task_type, status, input_snapshot, budget_limit_cents, max_attempts, provider, model, prompt_version) values (candidate.episode_id, 'generate_review_render', 'ready', jsonb_build_object('capability','review_rendering','allowed_tools',jsonb_build_array('read','write'),'review_render',jsonb_build_object('pre_render_review_package_id',candidate.pre_render_review_package_id,'composition_revision_id',composition.id,'project_revision',composition.revision_number,'project_relative_path',project_path,'storyboard',candidate.context_snapshot->'storyboard','members',members,'adjustments',jsonb_build_object('caption_style',composition.caption_style,'pacing',composition.pacing,'crop',composition.crop,'transition',composition.transition,'layout',composition.layout,'reason',composition.reason)),'input_artifacts',inputs,'output',jsonb_build_object('required_artifact_types',jsonb_build_array('render','review_render_project','review_render_runtime','review_qc_report'),'content_type','video/mp4','relative_path',render_path,'review_stage','qc_review')),0,1,'hyperframes','hyperframes@0.7.109','review-render-v2') returning * into created_task;
    return next created_task;
  end loop;
end; $$;

create or replace function public.register_completed_review_render()
returns trigger language plpgsql security definer set search_path = '' as $$
declare render_artifact public.artifacts; qc_artifact public.artifacts; task_run public.task_runs; package public.review_packages; next_revision integer; previous_stage public.episode_stage;
begin
  if new.status <> 'completed' or new.task_type <> 'generate_review_render' or old.status = 'completed' then return new; end if;
  select * into render_artifact from public.artifacts where producer_task_id = new.id and artifact_type = 'render' and relative_path = new.input_snapshot #>> '{output,relative_path}';
  select * into qc_artifact from public.artifacts where producer_task_id = new.id and artifact_type = 'review_qc_report';
  select * into task_run from public.task_runs where task_id = new.id and attempt = new.attempt - 1;
  if not found or render_artifact.id is null or qc_artifact.id is null then raise exception 'Completed review render is missing QC evidence' using errcode = '22023'; end if;
  select coalesce(max(revision_number), 0) + 1 into next_revision from public.review_packages where episode_id = new.episode_id and stage = 'qc_review';
  insert into public.review_packages (episode_id,task_id,task_run_id,artifact_id,stage,revision_number,context_snapshot) values (new.episode_id,new.id,task_run.id,render_artifact.id,'qc_review',next_revision,jsonb_build_object('review_kind','hyperframes_review_render','pre_render_review_package_id',new.input_snapshot #>> '{review_render,pre_render_review_package_id}','composition_revision_id',new.input_snapshot #>> '{review_render,composition_revision_id}','composition_adjustments',new.input_snapshot #> '{review_render,adjustments}','project_revision',new.input_snapshot #>> '{review_render,project_revision}','project_relative_path',new.input_snapshot #>> '{review_render,project_relative_path}','qc_report',jsonb_build_object('artifact_id',qc_artifact.id,'relative_path',qc_artifact.relative_path,'sha256',qc_artifact.sha256,'file_size',qc_artifact.file_size),'frozen_input_artifacts',new.input_snapshot -> 'input_artifacts','technical_evidence',new.last_result -> 'validation')) returning * into package;
  select stage into previous_stage from public.episodes where id = new.episode_id for update; if previous_stage <> 'render_ready' then raise exception 'Review render completed outside render_ready stage' using errcode = '22023'; end if;
  update public.episodes set stage = 'qc_review', updated_at = now() where id = new.episode_id; insert into public.state_transitions (episode_id,from_stage,to_stage,reason,actor_id) values (new.episode_id,'render_ready','qc_review','HyperFrames deterministic review render completed.',null);
  insert into public.audit_events (account_id,episode_id,event_type,payload,actor_id) select episode.account_id,episode.id,'review_render_created',jsonb_build_object('review_package_id',package.id,'task_id',new.id,'project_revision',new.input_snapshot #>> '{review_render,project_revision}'),null from public.episodes episode where episode.id = new.episode_id;
  return new;
end; $$;

create unique index if not exists tasks_one_final_render_per_qc_package_idx on public.tasks (episode_id, (input_snapshot #>> '{final_render,source_review_package_id}')) where task_type = 'generate_final_render';

create or replace function public.orchestrate_final_render_tasks(p_episode_id uuid default null)
returns setof public.tasks language plpgsql security definer set search_path = '' as $$
declare candidate record; created_task public.tasks; output_path text; project_path text;
begin
  for candidate in select episode.id as episode_id, package.id as package_id, source.input_snapshot as source_snapshot, project_artifact.*, runtime_artifact.id as runtime_id, runtime_artifact.relative_path as runtime_relative_path, runtime_artifact.sha256 as runtime_sha256, runtime_artifact.file_size as runtime_file_size, qc_artifact.id as qc_id, qc_artifact.relative_path as qc_relative_path, qc_artifact.sha256 as qc_sha256, qc_artifact.file_size as qc_file_size from public.episodes episode join lateral (select package.* from public.review_packages package join public.approvals approval on approval.review_package_id = package.id and approval.stage = 'qc_passed' and approval.decision = 'approved' where package.episode_id = episode.id and package.stage = 'qc_review' and package.invalidated_at is null order by package.revision_number desc limit 1) package on true join public.tasks source on source.id = package.task_id and source.status = 'completed' join public.artifacts project_artifact on project_artifact.producer_task_id = source.id and project_artifact.artifact_type = 'review_render_project' join public.artifacts runtime_artifact on runtime_artifact.producer_task_id = source.id and runtime_artifact.artifact_type = 'review_render_runtime' join public.artifacts qc_artifact on qc_artifact.producer_task_id = source.id and qc_artifact.artifact_type = 'review_qc_report' where episode.stage = 'qc_passed' and (p_episode_id is null or episode.id = p_episode_id) order by episode.updated_at, episode.id for update of episode skip locked loop
    if exists (select 1 from public.tasks task where task.episode_id = candidate.episode_id and task.task_type = 'generate_final_render' and task.input_snapshot #>> '{final_render,source_review_package_id}' = candidate.package_id::text) then continue; end if;
    project_path := format('episodes/%s/final-render/v%s/index.html',candidate.episode_id,candidate.source_snapshot #>> '{review_render,project_revision}'); output_path := format('episodes/%s/final-render/v%s/final-render.mp4',candidate.episode_id,candidate.source_snapshot #>> '{review_render,project_revision}');
    insert into public.tasks (episode_id,task_type,status,input_snapshot,budget_limit_cents,max_attempts,provider,model,prompt_version) values (candidate.episode_id,'generate_final_render','ready',jsonb_build_object('capability','final_rendering','allowed_tools',jsonb_build_array('read','write'),'final_render',jsonb_build_object('source_review_package_id',candidate.package_id,'source_project',jsonb_build_object('artifact_type',candidate.artifact_type,'relative_path',candidate.relative_path,'sha256',candidate.sha256,'file_size',candidate.file_size),'source_runtime',jsonb_build_object('artifact_type','review_render_runtime','relative_path',candidate.runtime_relative_path,'sha256',candidate.runtime_sha256,'file_size',candidate.runtime_file_size),'source_qc_report',jsonb_build_object('artifact_type','review_qc_report','relative_path',candidate.qc_relative_path,'sha256',candidate.qc_sha256,'file_size',candidate.qc_file_size),'project_relative_path',project_path,'project_revision',(candidate.source_snapshot #>> '{review_render,project_revision}')::integer,'review_render',candidate.source_snapshot -> 'review_render'),'input_artifacts',(candidate.source_snapshot -> 'input_artifacts') || jsonb_build_array(jsonb_build_object('artifactType',candidate.artifact_type,'relativePath',candidate.relative_path,'sha256',candidate.sha256,'fileSize',candidate.file_size),jsonb_build_object('artifactType','review_render_runtime','relativePath',candidate.runtime_relative_path,'sha256',candidate.runtime_sha256,'fileSize',candidate.runtime_file_size),jsonb_build_object('artifactType','review_qc_report','relativePath',candidate.qc_relative_path,'sha256',candidate.qc_sha256,'fileSize',candidate.qc_file_size)),'output',jsonb_build_object('required_artifact_types',jsonb_build_array('final_render','final_render_project','final_qc_report'),'content_type','video/mp4','relative_path',output_path,'review_stage','qc_passed')),0,1,'hyperframes','hyperframes@0.7.109','final-render-v1') returning * into created_task; return next created_task;
  end loop;
end; $$;

create or replace function public.has_required_artifacts(p_episode_id uuid, p_to_stage public.episode_stage) returns boolean language sql stable set search_path = '' as $$
  select case p_to_stage
    when 'qc_passed'::public.episode_stage then exists (select 1 from public.review_packages package join public.artifacts report on report.producer_task_id = package.task_id and report.artifact_type = 'review_qc_report' where package.episode_id = p_episode_id and package.stage = 'qc_review' and package.invalidated_at is null)
    when 'publish_ready'::public.episode_stage then (select count(distinct artifact_type) = 5 and exists (select 1 from public.tasks verification join public.artifacts publish_package on publish_package.episode_id = verification.episode_id and publish_package.artifact_type = 'publish_package' where verification.episode_id = p_episode_id and verification.task_type = 'verify_publish_package' and verification.status = 'completed' and verification.input_snapshot #>> '{publish_package,sha256}' = publish_package.sha256 and (verification.input_snapshot #>> '{publish_package,file_size}')::bigint = publish_package.file_size) from public.artifacts where episode_id = p_episode_id and artifact_type in ('final_render','cover','metadata','final_qc_report','publish_package'))
    when 'script_approved'::public.episode_stage then exists (select 1 from public.artifacts where episode_id=p_episode_id and artifact_type='script')
    when 'visual_approved'::public.episode_stage then exists (select 1 from public.artifacts where episode_id=p_episode_id and artifact_type='visual_brief')
    when 'storyboard_approved'::public.episode_stage then exists (select 1 from public.artifacts where episode_id=p_episode_id and artifact_type='storyboard') else true end;
$$;

revoke all on function public.orchestrate_review_render_tasks(uuid), public.orchestrate_final_render_tasks(uuid), public.register_completed_review_render() from public, anon, authenticated;
grant execute on function public.orchestrate_review_render_tasks(uuid), public.orchestrate_final_render_tasks(uuid) to service_role;

create or replace function public.record_publish_package(p_episode_id uuid, p_relative_path text, p_sha256 text, p_file_size bigint)
returns public.artifacts language plpgsql security definer set search_path = '' as $$
declare current_episode public.episodes; recorded_artifact public.artifacts; publish_task public.tasks; expected_path text;
begin
  if auth.role() is distinct from 'service_role' then raise exception 'Only the local publish-prep worker may record a publish package' using errcode = '42501'; end if;
  select * into current_episode from public.episodes where id = p_episode_id for update;
  if not found then raise exception 'Episode % does not exist', p_episode_id using errcode = 'P0002'; end if;
  if current_episode.stage <> 'qc_passed' then raise exception 'Publish package requires qc_passed' using errcode = '22023'; end if;
  expected_path := 'episodes/' || p_episode_id::text || '/publish-package/manifest.json';
  if p_relative_path <> expected_path or p_sha256 !~ '^[0-9a-f]{64}$' or p_file_size < 0 then raise exception 'Publish package index is invalid' using errcode = '22023'; end if;
  if not exists (select 1 from public.artifacts where episode_id = p_episode_id and artifact_type = 'final_render') or not exists (select 1 from public.artifacts where episode_id = p_episode_id and artifact_type = 'final_qc_report') then raise exception 'Final render and final QC report are required before a publish package' using errcode = '22023'; end if;
  select * into recorded_artifact from public.artifacts where episode_id = p_episode_id and artifact_type = 'publish_package' and relative_path = p_relative_path;
  if found then if recorded_artifact.sha256 <> p_sha256 or recorded_artifact.file_size <> p_file_size then raise exception 'Publish package is already fixed for this episode' using errcode = '22023'; end if; return recorded_artifact; end if;
  insert into public.tasks (episode_id,task_type,status,input_snapshot) values (p_episode_id,'prepare_publish_package','completed',jsonb_build_object('publish_package',jsonb_build_object('relative_path',p_relative_path,'sha256',p_sha256,'file_size',p_file_size))) returning * into publish_task;
  insert into public.artifacts (episode_id,artifact_type,relative_path,sha256,file_size,producer_task_id) values (p_episode_id,'publish_package',p_relative_path,p_sha256,p_file_size,publish_task.id) returning * into recorded_artifact;
  insert into public.audit_events (account_id,episode_id,event_type,payload,actor_id) values (current_episode.account_id,p_episode_id,'publish_package_generated',jsonb_build_object('relative_path',p_relative_path,'sha256',p_sha256,'file_size',p_file_size),auth.uid()); return recorded_artifact;
end; $$;
revoke all on function public.record_publish_package(uuid,text,text,bigint) from public, anon, authenticated;
grant execute on function public.record_publish_package(uuid,text,text,bigint) to service_role;
